### ISSUE TITLE
initialize key(What is key?)

### ISSUE THREAD

**Issue by toanbbc** [xaldarof/encrypted-shared-preferences#1]
hello my friends! I don't understand what is the key in initialize function?

**Comment by xaldarof** [comment]
Hi, it is encryption key(16 length) for shared_preferneces.

**Comment by xaldarof** [comment]
For example:
final String exampleEncryptionKey = "1234567891234567";
await EncryptedSharedPreferences.initialize(exampleEncryptionKey);
