### ISSUE TITLE
I can use both SharedPreferences and EncryptedSharedPreferences ?

### ISSUE THREAD

**Issue by jidanyu** [xaldarof/encrypted-shared-preferences#12]
For the missing API like setStringList, I can use SharedPreferences.getInstance(); separately for storage. And I can use EncryptedSharedPreferences only for the KV that needs to be encrypted.
```const key = "my_secret_key123";
 _storage ??= await SharedPreferences.getInstance();
await EncryptedSharedPreferences.initialize(key);
_encryptedStorage ??= EncryptedSharedPreferences.getInstance();
```
   
Will there be any problem using it this way?

**Comment by xaldarof** [comment]
Hi, you can check [encrypt_shared_preferences: ^0.8.1](https://pub.dev/packages/encrypt_shared_preferences) new version for missing setStringList method :)

**Comment by xaldarof** [comment]
> Hi, you can check [encrypt_shared_preferences: ^0.8.1](https://pub.dev/packages/encrypt_shared_preferences) new version for missing setStringList method :)

![Снимок экрана 2024-11-21 в 17 58 08](https://github.com/user-attachments/assets/4fdcfbe7-59f3-470e-be4f-b024f4569c0b)
