### ISSUE TITLE
initialization failed, key not set

### ISSUE THREAD

**Issue by ananghariyanto-bmkg** [xaldarof/encrypted-shared-preferences#14]
Hi, i want to use your library on my flutter apps, when i run my apps on Android it's working just fine, but when i try to debug it on iOS, i got this error

Exception has occurred.
`_AssertionError ('package:encrypt_shared_preferences/src/enc_shared_pref_async.dart': Failed assertion: line 17 pos 12: '_key != null': is not true.).`

Even though i've initialized it on the main.dart like this

`await EncryptedSharedPreferencesAsync.initialize(
        EbmkgEncryptedPreferences.encrpytionKey);`

what' s likely to be the problem?

**Comment by xaldarof** [comment]
Hi, can u share your key Length?

**Comment by ananghariyanto-bmkg** [comment]
this is my key for now,

`static const encrpytionKey = 'a2c4e6g8i0kxxxxx';`

i could changed it later

**Comment by xaldarof** [comment]
Is your IOS real or simulator? And which model?

**Comment by xaldarof** [comment]
> Is your IOS real or simulator? And which model?

Can u share example code for testing on my device?

**Comment by ananghariyanto-bmkg** [comment]
sorry for the unclear information, 
I'm using Macbook Pro M3 Pro, and i debug it on iPhone 15 Simulator

**Comment by xaldarof** [comment]
Now I checked with latest version, it works on my device.

**Comment by xaldarof** [comment]
Can you share your main function?

**Comment by ananghariyanto-bmkg** [comment]
> > Is your IOS real or simulator? And which model?
> 
> Can u share example code for testing on my device?

So, i develop my flutter Apps using Riverpod for the state management. As i mentioned above, i initialized your lib on the main.dart like this 

```
void main() async {
    await EncryptedSharedPreferencesAsync.initialize(
            EbmkgEncryptedPreferences.encrpytionKey);

    runApp(const ProviderScope(child: HomeApp());
}
```

here is the provider declaration for the riverpod

```
final ebmkgEncryptedPrefsProvider = Provider<EbmkgEncryptedPreferences>((ref) {
  return EbmkgEncryptedPreferences();
});
```


EbmkgEncryptedPreferences class
```
class EbmkgEncryptedPreferences {
  static const encrpytionKey = 'a2c4e6g8i0kxxxxx';
  final _ePrefs = EncryptedSharedPreferencesAsync.getInstance();
}
```

**Comment by xaldarof** [comment]
You can check   encrypt_shared_preferences: ^0.7.6 version for temporary solution, I reproduced your case. I will update package version soon.

**Comment by ananghariyanto-bmkg** [comment]
i'll check it

**Comment by xaldarof** [comment]
Ok, In this version there is no EncryptedSharedPreferencesAsync u should use EncryptedSharedPreferences class

**Comment by ananghariyanto-bmkg** [comment]
It's the same, my previous code is using just EncryptedSharedPreferences class, when i check the documentation there s EncryptedSharedPreferencesAsync in the newest version, so i want to try that one, and the problem is the same

**Comment by xaldarof** [comment]
Did u downgraded package version?

**Comment by ananghariyanto-bmkg** [comment]
i just tried to downgrade the version, it gives the same error
<img width="899" alt="Screenshot 2024-12-12 at 20 48 59" src="https://github.com/user-attachments/assets/f7c67f33-6f15-47ce-946f-69f36a10c4a4" />

**Comment by xaldarof** [comment]
can I share example project?

**Comment by ananghariyanto-bmkg** [comment]
Sure

**Comment by xaldarof** [comment]
Ok I will wait.

**Comment by ananghariyanto-bmkg** [comment]
wait, don't you mean you gonna share an example project to me?

**Comment by xaldarof** [comment]
I mean you should share example project where you use package.

**Comment by ananghariyanto-bmkg** [comment]
try this

https://github.com/ananghariyanto-bmkg/eprefs_retest

**Comment by xaldarof** [comment]
You should initialize WidgetsFlutterBinding

```
void main() async {
  try {
    debugPrint('Initializing EncryptedSharedPreferences');
    WidgetsFlutterBinding.ensureInitialized(); //Here
    await EncryptedSharedPreferences.initialize(
        EbmkgEncryptedPreferences.encrpytionKey);
  } catch (e) {}
  runApp(const ProviderScope(child: MyApp()));
}

```

**Comment by ananghariyanto-bmkg** [comment]
> WidgetsFlutterBinding.ensureInitialized();

my bad. but on my real project, i've initialized the WidgetsFlutterBinding in main too

**Comment by xaldarof** [comment]
In this example it works or not?

**Comment by ananghariyanto-bmkg** [comment]
> In this example it works or not?

it works

**Comment by ananghariyanto-bmkg** [comment]
it works now on my project, thanks

**Comment by xaldarof** [comment]
Thanks!
