### ISSUE TITLE
SharedPreferencesAsync.getString() return null value

### ISSUE THREAD

**Issue by HuynhThien82** [xaldarof/encrypted-shared-preferences#15]
Hi,
Firstly, thank you for your awesome contribution to the community. It helps me a lot from suffering. I found an issue with SharedPreferencesAsync.getString(), could you please check it?
Step to reproduce:

1. await setString() -> Return true
2. call await getString() immediately after step 1 with the same above key -> **_Return null value_** although the setString() result is true
3. But if I use hot restart or relaunch the app, now the return value of getString() is correct

I don't have this issue if I use EncryptedSharedPreferences without async

**Comment by xaldarof** [comment]
Hi thank you for your contribution, it helps me to improve this package, can u send MRP(example code)?

**Comment by HuynhThien82** [comment]
Here you go, I can reproduce it easily in a new flutter project.
`late EncryptedSharedPreferencesAsync encryptedSharedPreferences;`
  `final String _key = "key";`

  `@override`
  `void initState() {`
       `super.initState();`
       `encryptedSharedPreferences = EncryptedSharedPreferencesAsync.getInstance();`
 ` }`

  `@override`
  `void didChangeDependencies() async {`
    `super.didChangeDependencies();`
    `String? oldValue = await encryptedSharedPreferences.getString(_key);`
    `debugPrint("Old value: $oldValue");`
  `}`

  `void _incrementCounter() async {`
    `String? oldValue = await encryptedSharedPreferences.getString(_key);`
    `debugPrint("Old value: $oldValue");`
    `bool result = await encryptedSharedPreferences.setString(_key, "some value");`
    `debugPrint("Set result: $result");`
    `String? newValue = await encryptedSharedPreferences.getString(_key);`
    `debugPrint("New value: $newValue");`
  `}`

**Comment by xaldarof** [comment]
<img width="771" alt="image" src="https://github.com/user-attachments/assets/c2732664-4771-4241-a371-5bd38b293b7e" />

Log:

flutter: Old value: 9
flutter: Set result: true
flutter: New value: some value

**Comment by xaldarof** [comment]
I couldn't reproduce issue.

**Comment by HuynhThien82** [comment]
I tested with Android 15 Emulator and Android 14 Xiaomi Device. Here is the video

https://github.com/user-attachments/assets/fb3adf6e-9f9c-4f76-8471-c21b5f5893fd

**Comment by xaldarof** [comment]
Yeah I think I solved this issue, can you check 0.8.3 version of package?

https://pub.dev/packages/encrypt_shared_preferences

**Comment by HuynhThien82** [comment]
Thanks, but I can't check it now. I'll check it asap.

**Comment by HuynhThien82** [comment]
> Yeah I think I solved this issue, can you check 0.8.3 version of package?
> 
> https://pub.dev/packages/encrypt_shared_preferences

Confirmed,  this issue is fixed. Thank you so much.
