### ISSUE TITLE
How to call reload function?

### ISSUE THREAD

**Issue by Mingyueyixi** [xaldarof/encrypted-shared-preferences#2]
`EncryptedSharedPreferences`  miss reload function.
I found the `static late SharedPreferencesDecorator _decorator`  already implement, but it is private.
so , how can i call reload function?
or why it is private?

**Comment by xaldarof** [comment]
Hi, sorry for the confusion. I will update the package soon to solve problem.

**Comment by xaldarof** [comment]
Now you can check 0.4.9 version.

**Comment by Mingyueyixi** [comment]
thank you very much.I will try the version
