### ISSUE TITLE
Is this work on Flutter WEB?

### ISSUE THREAD

**Issue by khangpt** [xaldarof/encrypted-shared-preferences#6]
I already integrated this into my flutter web app, but every time close the browser. Then open again, all values I saved before been gone!
How can I accomplish this? Thanks for helping me

**Comment by xaldarof** [comment]
Hi, this package is a wrapper for [shared_preferences](https://pub.dev/packages/shared_preferences). You can create a new issue in the original repository.

**Comment by khangpt** [comment]
After a couple of time reading for this issue, I found that the latest version of shared_preferences package supports for flutter web. It worked when we build & deploy to somewhere hosting. In my case (development mode), I tested like: stop the running session, then start the other running session, in this time, the new instance of local server was started, I think that why my saved local data gone.

I leave this thread here, for others reference: [shared_preferences for flutter web](https://stackoverflow.com/questions/58678064/shared-preferences-for-flutter-web)

I appreciate for any feedback for me, thanks
